name: test

on:
  push:
    branches:
      - main


jobs:
  name: test
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Echo
      run: echo "This is a test for workflow\n"
      run: echo "Hello, world!\n"